---

- name: Install Filebeat
  ansible.builtin.include_tasks: beat-install.yml
  vars:
    _beat_name: filebeat

- name: Configure Filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart Filebeat
  tags:
    - configuration
    - beats_filebeat_configuration
    - beats_configuration

- name: Configure modules
  when: beats_filebeat_modules is defined
  tags:
    - configuration
    - beats_filebeat_configuration
    - beats_configuration
  block:

    - name: Enable modules
      ansible.builtin.command: "filebeat modules enable {{ item }}"
      args:
        creates: "/etc/filebeat/modules.d/{{ item }}.yml"
      loop: "{{ beats_filebeat_modules }}"

    - name: Enable System module
      ansible.builtin.template:
        src: filebeat-system.yml.j2
        dest: /etc/filebeat/modules.d/system.yml
        owner: root
        group: root
        mode: 0644
      when:
        - elasticstack_release | int > 7

    - name: Enable Ingest Pipelines
      ansible.builtin.shell: >
        /usr/bin/filebeat setup --pipelines &&
        /usr/bin/filebeat version > /etc/filebeat/{{ item }}_pipeline_created
      args:
        creates: "/etc/filebeat/{{ item }}_pipeline_created"
      loop: "{{ beats_filebeat_modules }}"
      notify:
        - Restart Filebeat

- name: Start Filebeat
  ansible.builtin.service:
    name: filebeat
    state: started
    enabled: true
  when: beats_filebeat_enable | bool
