galaxy_info:
  author: Netways GmbH
  description: Elasticsearch Ansible role
  role_name: elasticsearch
  company: Netways GmbH
  namespace: oddly
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags: []
dependencies: []
