galaxy_info:
  role_name: kibana
  author: netways
  description: Ansible role for Kibana
  company: Netways GmbH
  license: GPL-3.0-or-later

  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags: []
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
