galaxy_info:
  role_name: elasticstack_repos
  namespace: oddly
  description: Elastic Repositories
  author: Thomas Widhalm <thomas.widhalm@netways.de>
  company: oddly
  license: GPL-3.0-or-later

  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - logmanagement
    - elasticstack

dependencies: []
