---
galaxy_info:
  role_name: logstash
  author: netways
  description: Logstash for Linux
  company: "Netways GmbH"
  license: license (GPL-3.0-or-later)
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - elk
    - logstash
    - logging
    - system
dependencies: []
