---
galaxy_info:
  role_name: logstash
  author: oddly
  description: Logstash for Linux
  company: oddly
  license: license (GPL-3.0-or-later)
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - elk
    - logstash
    - logging
    - system
dependencies: []
