---
name: Test Linting
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  workflow_call:
    inputs:
      rolename:
        required: true
        type: string
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3.12
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Install test dependencies.
        run: uv pip install --system -r requirements-test.txt
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

      - name: Lint code (yamllint).
        run: |
          yamllint .
        if: ${{ inputs.rolename == '' }}

      - name: Lint Role (yamllint).
        run: |
          yamllint roles/${{ inputs.rolename }}
        if: ${{ inputs.rolename != '' }}

      - name: Lint Role (ansible-lint).
        run: |
          ansible-lint roles/${{ inputs.rolename }}
